config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :goods
  resources :consent_forms
  resources :consent_form_types
  resources :donations
      get  'confirm_donation', to: 'donations#confirm'
      post 'confirm_donation', to: 'donations#confirm'
      get  'collect_donation', to: 'donations#collect'
      post 'collect_donation', to: 'donations#collect'
      get  'abort_donation', to: 'donations#abort'
      post 'abort_donation', to: 'donations#abort'
    
  resources :cities
  resources :states
  resources :countries
  resources :volunteers
    get 'volunteer', to: 'volunteers#menu'
  resources :suppliers
  resources :consumers
  resources :donors
    get 'donor', to: 'donor#donor'
	get 'donate', to: 'donor#donate'
	get 'track_donations', to: 'donor#track_donations'
	get 'list_donations', to: 'donor#list_donations'

 
  resources :donation_campaigns
  resources :address_cocoons
  resources :person_cocoons
  resources :services
  resources :ranks
  resources :form_contacts
  resources :addresses
  resources :private_place_types
  resources :public_places
  resources :supply_food_configurations
  resources :postal_code_hints
  get 'postal_code_hints_search', to: 'postal_code_hints#search'
  post 'postal_code_hints_search', to: 'postal_code_hints#search'
  resources :measure_units
  resources :good_types
  resources :levels
  resources :logs
  resources :user_types
  resources :address_types
  resources :public_place_types
  resources :person_types
  resources :ic_types
  resources :people
  resources :assignment_types
  resources :form_contacts
    
  root 'splash#splash'
  get 'home', to: 'home#home'
  get 'about', to: 'home#about'
  get 'my_jquery_test', to: 'home#my_jquery_test'
  get 'point_hunger', to: 'home#point_hunger'
  
  if Rails.env.development?
       get 'testbootstrap', to: 'home#testbootstrap'
  end
 
  get 'foodhandling', to: 'home#foodhandling'
  get 'news', to: 'home#news'
  get 'legal', to: 'home#legal'
  get 'services', to: 'home#services'
  get 'valueofdonation', to: 'home#valueofdonation'
    
  get 'main_tables_management', to: 'management#main_tables'
  get 'manager_management', to: 'management#manager'
  get 'volunteer_management', to: 'management#volunteer'
  get 'supplier_management', to: 'management#supplier'
  get 'donee_management', to: 'management#donee'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donor.rb
class Donor < ApplicationRecord
    belongs_to :user
    has_many :donations
    
    def getStartLevel
        @@donor_start_level ||="#{SupplyFoodConfiguration.find_by(name: "Donor start level").description}"
    end
end

app/controllers/donor_controller.rb
class DonorController < ApplicationController
    
def donor
end
# GET /donataion/new
def new_donataion
    @donation =Donation.new
end
# POST /donation
# POST /donation.json
def donate
    #donate
    
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation request sent.' }
        format.json { render :donate, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
end

def track_donations
    track_donations
end
    
def list_donations
    list_donations
end
    
private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donor_params
      params.require(:donor).permit(:donor_id,  donation_attributes: [:good_type_id, :qty, :measure_unit_id,:address_id, :_destroy])
    end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: [:show, :edit, :update, :destroy]

  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
  end

  # GET /donors/new
  def new
    @donor = Donor.new
  end

  # GET /donors/1/edit
  def edit
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(donor_params)

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render :show, status: :created, location: @donor }
      else
        format.html { render :new }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donors/1
  # PATCH/PUT /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_url, notice: 'Donor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donor_params
      params.require(:donor).permit()
    end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_form.html.erb
<%= form_with(model: donor, local: true) do |form| %>
  <% if donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% donor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :person_id %>
    <%= form.text_field :person_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing Donor</h1>

<%= render 'form', donor: @donor %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donors</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donors.each do |donor| %>
      <tr>
        <td><%= donor.id %></td>
        <td><%= donor.user %></td>
        <td><%= donor.created_at %></td>
        <td><%= donor.updated_at %></td>
        <td><%= link_to 'Show', donor %></td>
        <td><%= link_to 'Edit', edit_donor_path(donor) %></td>
        <td><%= link_to 'Destroy', donor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donor', new_donor_path %>

app/views/donors/new.html.erb
<h1>New Donor</h1>

<%= render 'form', donor: @donor %>

<%= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @donor.person %>
</p>

<%= link_to 'Edit', edit_donor_path(@donor) %> |
<%= link_to 'Back', donors_path %>