config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :goods
  resources :consent_forms
  resources :consent_form_types
  resources :donations
      get  'confirm_donation', to: 'donations#confirm'
      post 'confirm_donation', to: 'donations#confirm'
      get  'collect_donation', to: 'donations#collect'
      post 'collect_donation', to: 'donations#collect'
      get  'abort_donation', to: 'donations#abort'
      post 'abort_donation', to: 'donations#abort'
    
  resources :cities
  resources :states
  resources :countries
  resources :volunteers
    get 'volunteer', to: 'volunteers#menu'
  resources :suppliers
  resources :consumers
  resources :donors
    get 'donor', to: 'donor#donor'
	get 'donate', to: 'donor#donate'
	get 'track_donations', to: 'donor#track_donations'
	get 'list_donations', to: 'donor#list_donations'

 
  resources :donation_campaigns
  resources :address_cocoons
  resources :person_cocoons
  resources :services
  resources :ranks
  resources :form_contacts
  resources :addresses
  resources :private_place_types
  resources :public_places
  resources :supply_food_configurations
  resources :postal_code_hints
  get 'postal_code_hints_search', to: 'postal_code_hints#search'
  post 'postal_code_hints_search', to: 'postal_code_hints#search'
  resources :measure_units
  resources :good_types
  resources :levels
  resources :logs
  resources :user_types
  resources :address_types
  resources :public_place_types
  resources :person_types
  resources :ic_types
  resources :people
  resources :assignment_types
  resources :form_contacts
    
  root 'splash#splash'
  get 'home', to: 'home#home'
  get 'about', to: 'home#about'
  get 'my_jquery_test', to: 'home#my_jquery_test'
  get 'point_hunger', to: 'home#point_hunger'
  
  if Rails.env.development?
       get 'testbootstrap', to: 'home#testbootstrap'
  end
 
  get 'foodhandling', to: 'home#foodhandling'
  get 'news', to: 'home#news'
  get 'legal', to: 'home#legal'
  get 'services', to: 'home#services'
  get 'valueofdonation', to: 'home#valueofdonation'
    
  get 'main_tables_management', to: 'management#main_tables'
  get 'manager_management', to: 'management#manager'
  get 'volunteer_management', to: 'management#volunteer'
  get 'supplier_management', to: 'management#supplier'
  get 'donee_management', to: 'management#donee'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donation.rb
class Donation < ApplicationRecord
 belongs_to :donor 
 belongs_to :volunteer, optional: true 
 belongs_to :supplier, optional: true 
 has_many :goods, inverse_of: :donation, dependent: :destroy
 accepts_nested_attributes_for :goods, reject_if: :all_blank, allow_destroy: true
    

 def status
    #   Calculate the current status of a donation based on the following rules :
    #   open - no supplier nor volunteer
    #   assigned - no supplier but volunteer
    #   scheduled - supplier and volunteer
    #   collected - has supply
    #   stored - has inventory
    #   to delivery - has delivery
    #   delivering - has some good delivered
    #   delivered - has all goods delivered
     status_return="Not available"
     if self.supplier.nil? && self.volunteer.nil?
         status_return = "open"
     end
     status_return
 end
    
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  def confirm
  end
  
  def collect
  end
  
  def abort
  end
    
  
  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
      if consent_form_verification
      
          @donation = Donation.new

      end
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)
    
    @donation.donor = current_user.donor_find_or_create
    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def consent_form_verification
          #check if the current_user have the donation consent form filled    
          current_consent_form_type = ConsentFormType.find_by description: "Donor"
          current_consent_form = ConsentForm.find_by user: current_user, consent_form_type: current_consent_form_type
          if current_consent_form.nil? 
              #no consent 
              puts "!!!no consent"
              #create the consent end redirect to be signed
               current_consent_form = ConsentForm.new
               current_consent_form.consent_form_type = ConsentFormType.find_by description: "Donor"
               current_consent_form.origin_url = "/donations/new"
               current_consent_form.user = current_user
               current_consent_form.save

              redirect_to  edit_consent_form_path (current_consent_form)
          elsif !current_consent_form.is_signed
              #consent form must be signed
              puts "!!!not signed"
              redirect_to  edit_consent_form_path (current_consent_form)
          elsif !current_consent_form.valid_until.nil? && current_consent_form.valid_until<Time.now
              #consent must be valid
              puts "!!!consent expired"
              redirect_to  edit_consent_form_path (current_consent_form)
          else
              #consent form ok
              #open new donation
              true
          end
    end
    
    
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:available_start, :available_end, :donor, :retrieve_address, :confirmation_phone, goods_attributes: [ :measure_unit_id, :good_type_id,:quantity, :expiration_date, :_destroy])
    end
    
    
end

app/helpers/donations_helper.rb
module DonationsHelper
    def addCounter
        #open donations file
        #"/resources/stats/stats.txt"
        #get donation value
        #donation_count=line1
        #add one
        donation_count++
        #save
        true
    end
    
    
    
end

app/views/donations/_form.html.erb
	<script>
		 $( function() {
			$( ".datetimepicker" ).datetimepicker();
			$( ".datepicker" ).datepicker({ format: "dd/mm/yyyy"});
			}	 );
    </script>

<%= form_with(model: donation, local: true,class: "form-horizontal") do |form| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group field">  
        <div class="control-label col-sm-8">
            <%= form.label "Your Name :" %>
            <% if current_user.full_name.nil? ||current_user.full_name.strip =="" %>
                <%= form.text_field :full_name, class:"form-control",placeholder:"eg : John Smith " %>
            <% else %>
                <%= current_user.full_name %>
            <% end %>
        </div>
    </div>

    <div class="form-group field">  
        <div class="control-label col-sm-16">
            <%= form.label "Collect the donation between" %>
        </div>

		<div class="row">
			<div class="col-sm-4">
				<%= form.text_field :available_start, class:"form-control field datetimepicker" %> and 
				<%= form.text_field :available_end, class:"form-control field datetimepicker" %>
			</div>
		</div>

    </div>
<hr>

<h2>Retrieve Address</h2>
    <div class="form-group field">  
        <div class="col-sm-4">
            <%= form.text_field :retrieve_address, class:"form-control",placeholder:"eg : Broadway " %>
        </div>
         <div class="control-label col-sm-4">
            <%= form.label "Area of activity , Country/State/City :" %>&nbsp;<%= SupplyFoodConfiguration.get_favourite_location %>
        </div>
        
    </div>

    
    <div class="form-group field">  
        <div class="control-label col-sm-4">
            <%= form.label :confirmation_phone  %>
        </div>
        <div class="col-sm-3">
            <%= form.text_field :confirmation_phone, class:"form-control",placeholder:"eg : 999-999-9999 " %>
        </div>
    </div>
<hr>
<h2>Donation Goods</h2>
<div id="goods_sub_form">
    <%= form.fields_for :goods do |good| %>
        <% render "good_fields", :f => good %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add good',form, :goods %>
    </div>
</div>






<hr>

    <%= link_to "","send mongo", remote: true, class: 'btn btn-xs btn-success',  onmousedown: "addDonation(event);"  %>
    <div class="actions">
    <%= form.submit %>
    </div>
<% end %>

app/views/donations/_good_fields.html.erb
<h2>Goods</h2>

	  <script>
  $( function() {
    $( ".datepickerSubGood" ).datepicker();
  } );
    </script>
    <div class="form-group nested-fields">  
        
        <div class="control-label col-sm-4">
                <%= f.label :good_type %>
                <%= f.collection_select( :good_type_id , GoodType.all, :id, :name,class:"form-control field" )%>
        </div>
        
        <div class="control-label col-sm-4">
                <%= f.label :quantity %>
                <%= f.text_field :quantity, class:"form-control field", placeholder:"eg : 5" %>
        </div>
        
        <div class="control-label col-sm-4">
                <%= f.label :measure_unit %>
                <%= f.collection_select( :measure_unit_id,  MeasureUnit.all, :id, :name,class:"form-control field" ) %>
        </div>

        <div class="control-label col-sm-4 ">
            <%= f.label :expiration_date %>
			<%= f.text_field :expiration_date, class:"form-control field datepickerSubGood" %>
        </div>
		
    </div>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form', donation: @donation %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donations</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Created at</th>
      <th>Available start</th>
      <th>Available end</th>
      <th>Donor</th>
      <th>Courier</th>
      <th>Volunteer</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= link_to donation.id, donation, class:"btn btn-outline-primary btn-sm" %> </td>
        <td><%= donation.created_at %></td>
        <td><%= donation.available_start %></td>
        <td><%= donation.available_end %></td>
        <td><%= User.find_by("donor_id = #{donation.donor.id}").full_name %></td>
        <td><%= donation.supplier %></td>
        <td><%= donation.volunteer %></td>
        <td><%= donation.status %></td>     
        <td><%= link_to 'Collect', confirm_donation_path(donation), class:"btn btn-outline-primary btn-sm" %>
        <%= link_to 'Receive', collect_donation_path(donation), class:"btn btn-outline-primary btn-sm" %><%= link_to 'Abort', abort_donation_path(donation), class:"btn btn-outline-primary btn-sm" %><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-primary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Offline Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>Schedule a Donation</h1>

<%= render 'form', donation: @donation %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>



  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div >  
        <div >
             <strong>Your Name :</strong>   
                <%= current_user.full_name %>
        </div>
    </div>

    <div  >  
        <div  >
            <strong>Collect the donation between </strong>
        </div>

		<div class="row">
			<div class="col-sm-12">
				<%= @donation.available_start  %> and 
				<%= @donation.available_end  %>
			</div>
		</div>

    </div>
<hr>

<h2>Retrieve Address</h2>
    <div >  
        <div class="col-sm-4">
            <%= @donation.retrieve_address  %>
        </div>
         <div class="control-label col-sm-12">
            Area of activity , 
             Country/State/City : &nbsp;
            <%= SupplyFoodConfiguration.get_favourite_location %>
        </div>
        
    </div>

    
    <div  >  
        <div class="col-sm-4">
            <%= @donation.confirmation_phone  %>
        </div>
    </div>
<hr>
<h2>Donation Goods</h2>
<div  >
    <%= @donation.goods.each do |good| %>
        <%# render "good_fields_show", :f => good %>
    <% end %>
</div>