config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :goods
  resources :consent_forms
  resources :consent_form_types
  resources :donations
      get  'confirm_donation', to: 'donations#confirm'
      post 'confirm_donation', to: 'donations#confirm'
      get  'collect_donation', to: 'donations#collect'
      post 'collect_donation', to: 'donations#collect'
      get  'abort_donation', to: 'donations#abort'
      post 'abort_donation', to: 'donations#abort'
    
  resources :cities
  resources :states
  resources :countries
  resources :volunteers
    get 'volunteer', to: 'volunteers#menu'
  resources :suppliers
  resources :consumers
  resources :donors
    get 'donor', to: 'donor#donor'
	get 'donate', to: 'donor#donate'
	get 'track_donations', to: 'donor#track_donations'
	get 'list_donations', to: 'donor#list_donations'

 
  resources :donation_campaigns
  resources :address_cocoons
  resources :person_cocoons
  resources :services
  resources :ranks
  resources :form_contacts
  resources :addresses
  resources :private_place_types
  resources :public_places
  resources :supply_food_configurations
  resources :postal_code_hints
  get 'postal_code_hints_search', to: 'postal_code_hints#search'
  post 'postal_code_hints_search', to: 'postal_code_hints#search'
  resources :measure_units
  resources :good_types
  resources :levels
  resources :logs
  resources :user_types
  resources :address_types
  resources :public_place_types
  resources :person_types
  resources :ic_types
  resources :people
  resources :assignment_types
  resources :form_contacts
    
  root 'splash#splash'
  get 'home', to: 'home#home'
  get 'about', to: 'home#about'
  get 'my_jquery_test', to: 'home#my_jquery_test'
  get 'point_hunger', to: 'home#point_hunger'
  
  if Rails.env.development?
       get 'testbootstrap', to: 'home#testbootstrap'
  end
 
  get 'foodhandling', to: 'home#foodhandling'
  get 'news', to: 'home#news'
  get 'legal', to: 'home#legal'
  get 'services', to: 'home#services'
  get 'valueofdonation', to: 'home#valueofdonation'
    
  get 'main_tables_management', to: 'management#main_tables'
  get 'manager_management', to: 'management#manager'
  get 'volunteer_management', to: 'management#volunteer'
  get 'supplier_management', to: 'management#supplier'
  get 'donee_management', to: 'management#donee'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/ic_types_controller.rb
class IcTypesController < ApplicationController
  before_action :set_ic_type, only: [:show, :edit, :update, :destroy]

  # GET /ic_types
  # GET /ic_types.json
  def index
    @ic_types = IcType.all.order("name")
  end

  # GET /ic_types/1
  # GET /ic_types/1.json
  def show
  end

  # GET /ic_types/new
  def new
    @ic_type = IcType.new
  end

  # GET /ic_types/1/edit
  def edit
  end

  # POST /ic_types
  # POST /ic_types.json
  def create
    @ic_type = IcType.new(ic_type_params)

    respond_to do |format|
      if @ic_type.save
        format.html { redirect_to @ic_type, notice: 'Ic type was successfully created.' }
        format.json { render :show, status: :created, location: @ic_type }
      else
        format.html { render :new }
        format.json { render json: @ic_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ic_types/1
  # PATCH/PUT /ic_types/1.json
  def update
    respond_to do |format|
      if @ic_type.update(ic_type_params)
        format.html { redirect_to @ic_type, notice: 'Ic type was successfully updated.' }
        format.json { render :show, status: :ok, location: @ic_type }
      else
        format.html { render :edit }
        format.json { render json: @ic_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ic_types/1
  # DELETE /ic_types/1.json
  def destroy
    @ic_type.destroy
    respond_to do |format|
      format.html { redirect_to ic_types_url, notice: 'Ic type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ic_type
      @ic_type = IcType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ic_type_params
      params.require(:ic_type).permit(:name)
    end
end

app/helpers/ic_types_helper.rb
module IcTypesHelper
end

app/views/ic_types/_form.html.erb
<%= form_with(model: ic_type, local: true,class: "form-horizontal") do |form| %>
  <% if ic_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ic_type.errors.count, "error") %> prohibited this ic_type from being saved:</h2>

      <ul>
      <% ic_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ic_types/edit.html.erb
<%= render 'management/tab' %>
<h2>Editing Identification Card Type</h2>

<%= render 'form', ic_type: @ic_type %>

<%= link_to 'Back', ic_types_path %>
<%= render 'management/tab-end' %>

app/views/ic_types/index.html.erb
<%= render 'management/tab' %>

<p id="notice"><%= notice %></p>

<h2>Identification Card Types</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Created at</th>
      <th scope="col">Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ic_types.each do |ic_type| %>
      <tr scope="row">
        <td><%= ic_type.name %></td>
        <td><%= ic_type.created_at %></td>
        <td><%= ic_type.updated_at %></td>
        <td><%= link_to 'Edit', edit_ic_type_path(ic_type) %></td>
        <td><%= link_to 'Destroy', ic_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ic Type', new_ic_type_path %>
<%= render 'management/tab-end' %>

app/views/ic_types/new.html.erb
<%= render 'management/tab' %>
<h2>New Identification Card Types</h2>

<%= render 'form', ic_type: @ic_type %>

<%= link_to 'Back', ic_types_path %>
<%= render 'management/tab-end' %>

app/views/ic_types/show.html.erb
<%= render 'management/tab' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ic_type.name %>
</p>

<%= link_to 'Edit', edit_ic_type_path(@ic_type) %> |
<%= link_to 'Back', ic_types_path %>
<%= render 'management/tab-end' %>